const SHEET_CSV_URL='https://docs.google.com/spreadsheets/d/e/2PACX-1vRRDjkaoyGRAQWhN8ZxFCXj1c0TdBvoEIQ_0JaBi6PX7Ym3ezvdk7b1ME9Q6ISveDuAHjTBp5gPFAA8/pub?output=csv';
const STATES=['Missouri','Illinois','Indiana','California','Nebraska','North Dakota','Pennsylvania'];
const STATE_NAMES={MO:'Missouri',IL:'Illinois',IN:'Indiana',CA:'California',NE:'Nebraska',ND:'North Dakota',PA:'Pennsylvania'};
const FALLBACK={Missouri:[38.4561,-92.2884],Illinois:[40,-89.2],Indiana:[39.8,-86.1],California:[36.8,-119.4],Nebraska:[41.5,-99.9],'North Dakota':[47.5,-100.5],Pennsylvania:[40.9,-77.8]};
let rows=[],activeFilter='all';
const maps={},layers={};
const $=id=>document.getElementById(id);
function normalizeState(v=''){v=String(v).trim();return STATE_NAMES[v.toUpperCase()]||STATES.find(s=>s.toLowerCase()===v.toLowerCase())||v}
function norm(v=''){return String(v).trim().toLowerCase().replace(/\s+/g,' ').replace(/[^a-z0-9 ]/g,'')}
function isTrue(v=''){return ['true','yes','y','1'].includes(String(v).trim().toLowerCase())}
function deriveStatus(r){const m=r.Member??r['Member Status']??'';const c=r.Contacted??r['Contacted Status']??'';const cat=String(r['Map Category']??r['Map Category (Automatic)']??'').trim().toLowerCase();if(isTrue(m)||cat==='member')return'Member';if(isTrue(c)||cat==='contacted'||cat==='contacted - non member'||cat==='contacted - non-member')return'Contacted';return'Not on Pro'}
function hasCoords(r){const lat=Number(String(r.Latitude).trim()),lon=Number(String(r.Longitude).trim());return r.Latitude!==''&&r.Longitude!==''&&Number.isFinite(lat)&&Number.isFinite(lon)}
function rank(s){return s==='Member'?3:s==='Contacted'?2:1}
function csvParse(text){const out=[];let row=[],field='',q=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(q&&text[i+1]==='"'){field+='"';i++}else q=!q}else if(c===','&&!q){row.push(field);field=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&text[i+1]==='\n')i++;row.push(field);field='';if(row.some(v=>v!==''))out.push(row);row=[]}else field+=c}if(field!==''||row.length){row.push(field);out.push(row)}if(!out.length)return[];const h=out[0].map(x=>String(x).trim());return out.slice(1).map(a=>{const o={};h.forEach((k,i)=>o[k]=String(a[i]??'').trim());o.State=normalizeState(o.State);o.Status=deriveStatus(o);return o})}
function dedupe(input){const seen=new Map();for(const r of input){r.State=normalizeState(r.State);r.Status=deriveStatus(r);const school=norm(r['School/District']),city=norm(r.City),address=norm(r.Address||r['Street Address']);const key=school?`${r.State}|${school}|${city}`:address?`${r.State}|${address}|${city}`:`${r.State}|${r.Latitude}|${r.Longitude}`;if(!seen.has(key)){seen.set(key,r);continue}const old=seen.get(key);if((hasCoords(r)&&!hasCoords(old))||rank(r.Status)>rank(old.Status))seen.set(key,{...old,...r,Status:r.Status})}return[...seen.values()]}
function color(s){return s==='Member'?'#4aa3ff':s==='Contacted'?'#ff9f1c':'#ff3b3f'}
function esc(x=''){return String(x).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function popup(r){return `<div class="popup-title">${esc(r['School/District'])}</div><div class="popup-status">${esc(r.Status)}</div><div class="popup-row">${esc(r.Address||r['Street Address']||'')}<br>${esc(r.City||'')} ${esc(r.ZIP||r.Zipcode||'')}</div>`}
function makeMap(state,index){const map=L.map(`map-${index}`,{zoomControl:false,attributionControl:index===6,scrollWheelZoom:false,doubleClickZoom:true,touchZoom:true,dragging:true,tap:true,keyboard:false,boxZoom:false});L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',{subdomains:'abcd',maxZoom:20,attribution:'&copy; OpenStreetMap contributors &copy; CARTO'}).addTo(map);maps[state]=map;layers[state]=L.layerGroup().addTo(map);map.setView(FALLBACK[state],5)}
function build(){const grid=$('mapsGrid');grid.innerHTML='';STATES.forEach((state,index)=>{const card=document.createElement('section');card.className='map-card';card.innerHTML=`<div id="map-${index}" class="map-canvas"></div><div class="map-title"><div class="name">${state}</div><div class="count" id="count-${index}"></div></div>`;grid.appendChild(card);makeMap(state,index)});render();setTimeout(()=>Object.values(maps).forEach(m=>m.invalidateSize()),250)}
function render(){STATES.forEach((state,index)=>{const layer=layers[state];layer.clearLayers();const data=rows.filter(r=>r.State===state&&hasCoords(r)&&(activeFilter==='all'||r.Status===activeFilter));const bounds=[];for(const r of data){const lat=Number(r.Latitude),lon=Number(r.Longitude);L.circleMarker([lat,lon],{radius:5,weight:1.4,color:'#ffffff',fillColor:color(r.Status),fillOpacity:.96,interactive:true,bubblingMouseEvents:false}).bindPopup(popup(r)).addTo(layer);bounds.push([lat,lon])}$(`count-${index}`).textContent=`${data.length.toLocaleString()} locations`;if(bounds.length)maps[state].fitBounds(bounds,{padding:[18,18],maxZoom:7});else maps[state].setView(FALLBACK[state],5)})}
$('filterBtn').addEventListener('click',e=>{e.currentTarget.blur();$('filterPanel').classList.toggle('open')});document.querySelectorAll('#filterPanel button').forEach(b=>b.addEventListener('click',()=>{activeFilter=b.dataset.filter;document.querySelectorAll('#filterPanel button').forEach(x=>x.classList.toggle('active',x===b));b.blur();$('filterPanel').classList.remove('open');render()}));
fetch(SHEET_CSV_URL,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`Sheet returned ${r.status}`);return r.text()}).then(t=>{rows=dedupe(csvParse(t));build()}).catch(e=>{console.error(e);$('loading').textContent='Could not load the school data.'}).finally(()=>{$('loading').style.display='none'});